check_inputs – bspline-fortran
check_inputs Subroutine
328 statements
Source File
private pure subroutine check_inputs(iknot, iflag, nx, ny, nz, nq, nr, ns, kx, ky, kz, kq, kr, ks, x, y, z, q, r, s, tx, ty, tz, tq, tr, ts, f1, f2, f3, f4, f5, f6, bcoef1, bcoef2, bcoef3, bcoef4, bcoef5, bcoef6, alt, status_ok)
Check the validity of the inputs to the db*ink routines. Prints warning message if there is an error, and also sets iflag and status_ok.
Supports up to 6D: x,y,z,q,r,s
Notes
The code is new, but the logic is based on the original logic in the CMLIB routines db2ink and db3ink.
History
Jacob Williams, 2/24/2015 : Created this routine.
Arguments
Type Intent Optional Attributes Name
integer(kind=ip), intent(in) :: iknot
= 0 if the INK routine is computing the knots.
integer(kind=ip), intent(out) :: iflag
integer(kind=ip), intent(in), optional :: nx
integer(kind=ip), intent(in), optional :: ny
integer(kind=ip), intent(in), optional :: nz
integer(kind=ip), intent(in), optional :: nq
integer(kind=ip), intent(in), optional :: nr
integer(kind=ip), intent(in), optional :: ns
integer(kind=ip), intent(in), optional :: kx
integer(kind=ip), intent(in), optional :: ky
integer(kind=ip), intent(in), optional :: kz
integer(kind=ip), intent(in), optional :: kq
integer(kind=ip), intent(in), optional :: kr
integer(kind=ip), intent(in), optional :: ks
real(kind=wp), intent(in), optional dimension(:) :: x
real(kind=wp), intent(in), optional dimension(:) :: y
real(kind=wp), intent(in), optional dimension(:) :: z
real(kind=wp), intent(in), optional dimension(:) :: q
real(kind=wp), intent(in), optional dimension(:) :: r
real(kind=wp), intent(in), optional dimension(:) :: s
real(kind=wp), intent(in), optional dimension(:) :: tx
real(kind=wp), intent(in), optional dimension(:) :: ty
real(kind=wp), intent(in), optional dimension(:) :: tz
real(kind=wp), intent(in), optional dimension(:) :: tq
real(kind=wp), intent(in), optional dimension(:) :: tr
real(kind=wp), intent(in), optional dimension(:) :: ts
real(kind=wp), intent(in), optional dimension(:) :: f1
real(kind=wp), intent(in), optional dimension(:,:) :: f2
real(kind=wp), intent(in), optional dimension(:,:,:) :: f3
real(kind=wp), intent(in), optional dimension(:,:,:,:) :: f4
real(kind=wp), intent(in), optional dimension(:,:,:,:,:) :: f5
real(kind=wp), intent(in), optional dimension(:,:,:,:,:,:) :: f6
real(kind=wp), intent(in), optional dimension(:) :: bcoef1
real(kind=wp), intent(in), optional dimension(:,:) :: bcoef2
real(kind=wp), intent(in), optional dimension(:,:,:) :: bcoef3
real(kind=wp), intent(in), optional dimension(:,:,:,:) :: bcoef4
real(kind=wp), intent(in), optional dimension(:,:,:,:,:) :: bcoef5
real(kind=wp), intent(in), optional dimension(:,:,:,:,:,:) :: bcoef6
logical, intent(in), optional :: alt
using the alt routine where 1st or 2nd deriv is fixed at endpoints [default is False]
logical, intent(out) :: status_ok
Calls
Called by
Contents
Variables
error iex
Subroutines
check check_n check_k check_x check_t
Variables
Type Visibility Attributes Name Initial
logical, private :: error
integer, private :: iex
extra points for the alt case (in t and bcoef) [currently, only allowed for the 1D case & k=4]
Subroutines
pure subroutine check(s, n, k, x, t, ierrs, iflag, error, ik)
check t,x,n,k for validity
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: s
coordinate string: 'x','y','z','q','r','s'
integer(kind=ip), intent(in), optional :: n
size of x
integer(kind=ip), intent(in), optional :: k
order
real(kind=wp), intent(in), optional dimension(:) :: x
abcissae vector
real(kind=wp), intent(in), optional dimension(:) :: t
knot vector size(n+k)
integer(kind=ip), intent(in), dimension(:) :: ierrs
int error codes for n,k,x,t, size(x),size(t) checks
integer(kind=ip), intent(out) :: iflag
status return code
logical, intent(out) :: error
true if there was an error
integer, intent(in) :: ik
add this value to k
pure subroutine check_n(s, n, x, ierr, iflag, error)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
integer(kind=ip), intent(in) :: n
real(kind=wp), intent(in), dimension(:) :: x
abcissae vector
integer(kind=ip), intent(in), dimension(2) :: ierr
[n<3 check, size(x)==n check]
integer(kind=ip), intent(out) :: iflag
status return code
logical, intent(out) :: error
pure subroutine check_k(s, k, n, ierr, iflag, error)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
integer(kind=ip), intent(in) :: k
integer(kind=ip), intent(in) :: n
integer(kind=ip), intent(in) :: ierr
integer(kind=ip), intent(out) :: iflag
status return code
logical, intent(out) :: error
pure subroutine check_x(s, n, x, ierr, iflag, error)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
integer(kind=ip), intent(in) :: n
real(kind=wp), intent(in), dimension(:) :: x
integer(kind=ip), intent(in) :: ierr
integer(kind=ip), intent(out) :: iflag
status return code
logical, intent(out) :: error
pure subroutine check_t(s, n, k, t, ierr, iflag, error)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
integer(kind=ip), intent(in) :: n
integer(kind=ip), intent(in) :: k
real(kind=wp), intent(in), dimension(:) :: t
integer(kind=ip), intent(in), dimension(2) :: ierr
[non-decreasing check, size check]
integer(kind=ip), intent(out) :: iflag
status return code
logical, intent(out) :: error
Call graph
check_inputs calls check
db4ink calls check_inputs
db1ink_alt calls check_inputs
db1ink_alt_2 calls check_inputs
db1ink_default calls check_inputs
db2ink calls check_inputs
db3ink calls check_inputs
db5ink calls check_inputs
db6ink calls check_inputs
initialize_4d_specify_knots calls db4ink
initialize_2d_auto_knots calls db2ink
initialize_6d_auto_knots calls db6ink
initialize_5d_auto_knots calls db5ink
initialize_4d_auto_knots calls db4ink
db1ink calls db1ink_alt, db1ink_alt_2, db1ink_default
initialize_3d_auto_knots calls db3ink
initialize_5d_specify_knots calls db5ink
initialize_3d_specify_knots calls db3ink
initialize_6d_specify_knots calls db6ink
initialize_2d_specify_knots calls db2ink
bspline_5d_constructor_specify_knots calls initialize_5d_specify_knots
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
initialize_1d_specify_knots calls db1ink
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_5d_constructor_auto_knots calls initialize_5d_auto_knots
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
initialize_1d_auto_knots calls db1ink
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
bspline_4d calls bspline_4d_constructor_specify_knots, bspline_4d_constructor_auto_knots
bspline_2d calls bspline_2d_constructor_auto_knots, bspline_2d_constructor_specify_knots
bspline_6d calls bspline_6d_constructor_specify_knots, bspline_6d_constructor_auto_knots
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_5d calls bspline_5d_constructor_specify_knots, bspline_5d_constructor_auto_knots
bspline_3d calls bspline_3d_constructor_specify_knots, bspline_3d_constructor_auto_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots