dbfqad – bspline-fortran
dbfqad Subroutine
63 statements
Source File
private subroutine dbfqad(f, t, bcoef, n, k, id, x1, x2, tol, quad, iflag, work)
dbfqad computes the integral on (x1,x2) of a product of a function f and the id-th derivative of a k-th order b-spline, using the b-representation (t,bcoef,n,k). (x1,x2) must be a subinterval of t(k) <= x <= t(n+1). an integration routine, dbsgq8 (a modification of gaus8), integrates the product on subintervals of (x1,x2) formed by included (distinct) knots
Reference
D. E. Amos, "Quadrature subroutines for splines and B-splines", Report SAND79-1825, Sandia Laboratories, December 1979.
History
800901 Amos, D. E., (SNLA)
890531 Changed all specific intrinsics to generic. (WRB)
890531 REVISION DATE from Version 3.2
891214 Prologue converted to Version 4.0 format. (BAB)
900315 CALLs to XERROR changed to CALLs to XERMSG. (THJ)
900326 Removed duplicate information from DESCRIPTION section. (WRB)
920501 Reformatted the REFERENCES section. (WRB)
Jacob Williams, 9/6/2017 : refactored to modern Fortran. Some changes.
Note
the maximum number of significant digits obtainable in dbsqad is the smaller of ~300 and the number of digits carried in real(wp) arithmetic.
Note
Extrapolation is not enabled for this routine.
Arguments
Type Intent Optional Attributes Name
procedure(b1fqad_func) :: f
external function of one argument for the integrand bf(x)=f(x)*dbvalu(t,bcoef,n,k,id,x,inbv,work)
real(kind=wp), intent(in), dimension(n+k) :: t
knot array
real(kind=wp), intent(in), dimension(n) :: bcoef
coefficient array
integer(kind=ip), intent(in) :: n
length of coefficient array
integer(kind=ip), intent(in) :: k
order of b-spline, k >= 1
integer(kind=ip), intent(in) :: id
order of the spline derivative, 0 <= id <= k-1 id=0 gives the spline function
real(kind=wp), intent(in) :: x1
left point of quadrature interval in t(k) <= x <= t(n+1)
real(kind=wp), intent(in) :: x2
right point of quadrature interval in t(k) <= x <= t(n+1)
real(kind=wp), intent(in) :: tol
desired accuracy for the quadrature, suggest 10*dtol < tol <= 0.1 where dtol is the maximum of 1.0e-300 and real(wp) unit roundoff for the machine
real(kind=wp), intent(out) :: quad
integral of bf(x) on (x1,x2)
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
1001: k does not satisfy k>=1
1002: n does not satisfy n>=k
1003: d does not satisfy 0<=id<k
1004: x1 or x2 or both do not satisfy t(k)<=x<=t(n+1)
1005: tol is less than dtol or greater than 0.1
real(kind=wp), intent(inout), dimension(:) :: work
work vector of length 3*k
Calls
Called by
Contents
Variables
inbv ilo il1 il2 left mflag npk np1 a aa ans b bb q ta tb err min_tol
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: inbv
integer(kind=ip), private :: ilo
integer(kind=ip), private :: il1
integer(kind=ip), private :: il2
integer(kind=ip), private :: left
integer(kind=ip), private :: mflag
integer(kind=ip), private :: npk
integer(kind=ip), private :: np1
real(kind=wp), private :: a
real(kind=wp), private :: aa
real(kind=wp), private :: ans
real(kind=wp), private :: b
real(kind=wp), private :: bb
real(kind=wp), private :: q
real(kind=wp), private :: ta
real(kind=wp), private :: tb
real(kind=wp), private :: err
real(kind=wp), private, parameter :: min_tol = max(epsilon(1.0_wp), 1.0e-300_wp)
minimum allowed tol
Call graph
dbfqad calls dintrv, dbsgq8
dintrv calls get_temp_x_for_extrap
dbsgq8 calls g8
dbvalu calls dintrv
db1fqad calls dbfqad
fintegral_1d calls db1fqad