dbint4 – bspline-fortran
dbint4 Subroutine
132 statements
Source File
private pure subroutine dbint4(x, y, ndata, ibcl, ibcr, fbcl, fbcr, kntopt, tleft, tright, t, bcoef, n, k, w, iflag)
DBINT4 computes the B representation (t,bcoef,n,k) of a cubic spline (k=4) which interpolates data (x(i),y(i)),i=1,ndata.
Parameters ibcl, ibcr, fbcl, fbcr allow the specification of the spline first or second derivative at both x(1) and x(ndata). When this data is not specified by the problem, it is common practice to use a natural spline by setting second derivatives at x(1) and x(ndata) to zero (ibcl=ibcr=2,fbcl=fbcr=0.0).
The spline is defined on t(4) <= x <= t(n+1) with (ordered) interior knots at x(i) values where n=ndata+2. The knots t(1),t(2),t(3) lie to the left of t(4)=x(1) and the knots t(n+2), t(n+3), t(n+4) lie to the right of t(n+1)=x(ndata) in increasing order.
If no extrapolation outside (x(1),x(ndata)) is anticipated, the knots t(1)=t(2)=t(3)=t(4)=x(1) and t(n+2)=t(n+3)=t(n+4)=t(n+1)=x(ndata) can be specified by kntopt=1.
kntopt=2 selects a knot placement for t(1), t(2), t(3) to make the first 7 knots symmetric about t(4)=x(1) and similarly for t(n+2), t(n+3), t(n+4) about t(n+1)=x(ndata).
kntopt=3 allows the user to make his own selection, in increasing order, for t(1), t(2), t(3) to the left of x(1) and t(n+2), t(n+3), t(n+4) to the right of x(ndata).
In any case, the interpolation on t(4) <= x <= t(n+1) by using function dbvalu is unique for given boundary conditions.
Error conditions
improper input
singular system of equations
See also
dbintk
History
Written by D. E. Amos (SNLA), August, 1979.
date written 800901
revision date 820801
Modified array declarations. (JEC)
Jacob Williams, 8/30/2018 : refactored to modern Fortran.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
x vector of abscissae of length ndata, distinct and in increasing order
real(kind=wp), intent(in), dimension(:) :: y
y vector of ordinates of length ndata
integer(kind=ip), intent(in) :: ndata
number of data points, ndata >= 2
integer(kind=ip), intent(in) :: ibcl
selection parameter for left boundary condition:
ibcl = 1 constrain the first derivative at x(1) to fbcl
ibcl = 2 constrain the second derivative at x(1) to fbcl
integer(kind=ip), intent(in) :: ibcr
selection parameter for right boundary condition:
ibcr = 1 constrain first derivative at x(ndata) to fbcr
ibcr = 2 constrain second derivative at x(ndata) to fbcr
real(kind=wp), intent(in) :: fbcl
left boundary values governed by ibcl
real(kind=wp), intent(in) :: fbcr
right boundary values governed by ibcr
integer(kind=ip), intent(in) :: kntopt
knot selection parameter:
kntopt = 1 sets knot multiplicity at t(4) and t(n+1) to 4
kntopt = 2 sets a symmetric placement of knots about t(4) and t(n+1)
kntopt = 3 sets t(i)=tleft(i) and t(n+1+i)=tright(i),i=1,3
real(kind=wp), intent(in), dimension(3) :: tleft
when kntopt = 3: t(1:3) in increasing order to be supplied by the user.
real(kind=wp), intent(in), dimension(3) :: tright
when kntopt = 3: t(n+2:n+4) in increasing order to be supplied by the user.
real(kind=wp), intent(out), dimension(:) :: t
knot array of length n+4
real(kind=wp), intent(out), dimension(:) :: bcoef
b spline coefficient array of length n
integer(kind=ip), intent(out) :: n
number of coefficients, n=ndata+2
integer(kind=ip), intent(out) :: k
order of spline, k=4
real(kind=wp), intent(inout), dimension(5,ndata+2) :: w
work array
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
2001: ndata is less than 2
2002: x values are not distinct or not ordered
2003: ibcl is not 1 or 2
2004: ibcr is not 1 or 2
2005: kntopt is not 1, 2, or 3
2006: knot input through tleft, tright is not ordered properly
2007: the system of equations is singular
Calls
Called by
Contents
Variables
i ilb ileft it iub iw iwp j jw ndm np nwrow txn tx1 xl vnikx work wdtol tol
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: i
integer(kind=ip), private :: ilb
integer(kind=ip), private :: ileft
integer(kind=ip), private :: it
integer(kind=ip), private :: iub
integer(kind=ip), private :: iw
integer(kind=ip), private :: iwp
integer(kind=ip), private :: j
integer(kind=ip), private :: jw
integer(kind=ip), private :: ndm
integer(kind=ip), private :: np
integer(kind=ip), private :: nwrow
real(kind=wp), private :: txn
real(kind=wp), private :: tx1
real(kind=wp), private :: xl
real(kind=wp), private, dimension(4,4) :: vnikx
real(kind=wp), private, dimension(15) :: work
work array for dbspvd -- length (k+1)*(k+2)/2
real(kind=wp), private, parameter :: wdtol = radix(1.0_wp)**(1-digits(1.0_wp))
d1mach(4)
real(kind=wp), private, parameter :: tol = sqrt(wdtol)
Call graph
dbint4 calls dbnslv, dbnfac, dbspvd
dbspvd calls dbspvn
db1ink_alt_2 calls dbint4
db1ink_alt calls dbint4
db1ink calls db1ink_alt_2, db1ink_alt
initialize_1d_specify_knots calls db1ink
initialize_1d_auto_knots calls db1ink
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots