dbnslv – bspline-fortran
dbnslv Subroutine
38 statements
Source File
private pure subroutine dbnslv(w, nroww, nrow, nbandl, nbandu, b)
Companion routine to dbnfac. it returns the solution x of the linear system a*x = b in place of b, given the lu-factorization for a in the work array w from dbnfac.
(with , as stored in w), the unit lower triangular system is solved for , and y stored in b. then the upper triangular system is solved for x. the calculations are so arranged that the innermost loops stay within columns.
History
banslv written by carl de boor [5]
dbnslv from SLATEC library [1]
Jacob Williams, 5/10/2015 : converted to free-form Fortran.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(nroww,nrow) :: w
describes the lu-factorization of a banded matrix a of order nrow as constructed in dbnfac.
integer(kind=ip), intent(in) :: nroww
describes the lu-factorization of a banded matrix a of order nrow as constructed in dbnfac.
integer(kind=ip), intent(in) :: nrow
describes the lu-factorization of a banded matrix a of order nrow as constructed in dbnfac.
integer(kind=ip), intent(in) :: nbandl
describes the lu-factorization of a banded matrix a of order nrow as constructed in dbnfac.
integer(kind=ip), intent(in) :: nbandu
describes the lu-factorization of a banded matrix a of order nrow as constructed in dbnfac.
real(kind=wp), intent(inout), dimension(nrow) :: b
in: right side of the system to be solved
out: the solution x, of order nrow
Called by
Contents
Source Code
dbnslv
Source Code
    pure subroutine dbnslv(w,nroww,nrow,nbandl,nbandu,b)
    integer(ip),intent(in) :: nroww   !! describes the lu-factorization of a banded matrix a of order `nrow`
                                      !! as constructed in [[dbnfac]].
    integer(ip),intent(in) :: nrow    !! describes the lu-factorization of a banded matrix a of order `nrow`
                                      !! as constructed in [[dbnfac]].
    integer(ip),intent(in) :: nbandl  !! describes the lu-factorization of a banded matrix a of order `nrow`
                                      !! as constructed in [[dbnfac]].
    integer(ip),intent(in) :: nbandu  !! describes the lu-factorization of a banded matrix a of order `nrow`
                                      !! as constructed in [[dbnfac]].
    real(wp),dimension(nroww,nrow),intent(in) :: w !! describes the lu-factorization of a banded matrix a of
                                                   !! order `nrow` as constructed in [[dbnfac]].
    real(wp),dimension(nrow),intent(inout) :: b  !! * **in**: right side of the system to be solved
                                                 !! * **out**: the solution x, of order nrow
    integer(ip) :: i, j, jmax, middle, nrowm1
    middle = nbandu + 1_ip
    if (nrow/=1_ip) then
        nrowm1 = nrow - 1_ip
        if (nbandl/=0_ip) then
            ! forward pass
            ! for i=1,2,...,nrow-1, subtract right side(i)*(i-th column of l)
            !                       from right side (below i-th row).
            do i=1_ip,nrowm1
                jmax = min(nbandl,nrow-i)
                do j=1_ip,jmax
                    b(i+j) = b(i+j) - b(i)*w(middle+j,i)
                end do
            end do
        end if
        ! backward pass
        ! for i=nrow,nrow-1,...,1, divide right side(i) by i-th diagonal
        !                          entry of u, then subtract right side(i)*(i-th column
        !                          of u) from right side (above i-th row).
        if (nbandu<=0_ip) then
            ! a is lower triangular.
            do i=1_ip,nrow
                b(i) = b(i)/w(1_ip,i)
            end do
            return
        end if
        i = nrow
        do
            b(i) = b(i)/w(middle,i)
            jmax = min(nbandu,i-1_ip)
            do j=1_ip,jmax
                b(i-j) = b(i-j) - b(i)*w(middle-j,i)
            end do
            i = i - 1_ip
            if (i<=1_ip) exit
        end do
    end if
    b(1_ip) = b(1_ip)/w(middle,1_ip)
    end subroutine dbnslv
Call graph
dbintk calls dbnslv
dbtpcf calls dbnslv, dbintk
dbint4 calls dbnslv
db5ink calls dbtpcf
db4ink calls dbtpcf
db1ink_alt calls dbint4
db1ink_alt_2 calls dbint4
db2ink calls dbtpcf
db3ink calls dbtpcf
db6ink calls dbtpcf
db1ink_default calls dbtpcf
initialize_4d_auto_knots calls db4ink
initialize_6d_specify_knots calls db6ink
initialize_6d_auto_knots calls db6ink
initialize_5d_auto_knots calls db5ink
db1ink calls db1ink_alt, db1ink_alt_2, db1ink_default
initialize_2d_specify_knots calls db2ink
initialize_2d_auto_knots calls db2ink
initialize_3d_specify_knots calls db3ink
initialize_5d_specify_knots calls db5ink
initialize_4d_specify_knots calls db4ink
initialize_3d_auto_knots calls db3ink
bspline_2d_constructor_specify_knots calls initialize_2d_specify_knots
initialize_1d_auto_knots calls db1ink
bspline_3d_constructor_specify_knots calls initialize_3d_specify_knots
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
initialize_1d_specify_knots calls db1ink
bspline_6d_constructor_auto_knots calls initialize_6d_auto_knots
bspline_4d_constructor_specify_knots calls initialize_4d_specify_knots
bspline_5d_constructor_specify_knots calls initialize_5d_specify_knots
bspline_3d_constructor_auto_knots calls initialize_3d_auto_knots
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_6d_constructor_specify_knots calls initialize_6d_specify_knots
bspline_5d_constructor_auto_knots calls initialize_5d_auto_knots
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_4d calls bspline_4d_constructor_auto_knots, bspline_4d_constructor_specify_knots
bspline_5d calls bspline_5d_constructor_specify_knots, bspline_5d_constructor_auto_knots
bspline_2d calls bspline_2d_constructor_specify_knots, bspline_2d_constructor_auto_knots
bspline_3d calls bspline_3d_constructor_specify_knots, bspline_3d_constructor_auto_knots
bspline_6d calls bspline_6d_constructor_auto_knots, bspline_6d_constructor_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots