dbsgq8 – bspline-fortran
dbsgq8 Subroutine
175 statements
Source File
private subroutine dbsgq8(fun, xt, bc, n, kk, id, a, b, inbv, err, ans, iflag, work)
DBSGQ8, a modification of gaus8, integrates the product of fun(x) by the id-th derivative of a spline dbvalu between limits a and b using an adaptive 8-point Legendre-Gauss algorithm.
See also
dbfqad
History
800901 Jones, R. E., (SNLA)
890531 Changed all specific intrinsics to generic. (WRB)
890911 Removed unnecessary intrinsics. (WRB)
891214 Prologue converted to Version 4.0 format. (BAB)
900315 CALLs to XERROR changed to CALLs to XERMSG. (THJ)
900326 Removed duplicate information from DESCRIPTION section. (WRB)
900328 Added TYPE section. (WRB)
910408 Updated the AUTHOR section. (WRB)
Jacob Williams, 9/6/2017 : refactored to modern Fortran. Some changes. Added higher precision coefficients.
Arguments
Type Intent Optional Attributes Name
procedure(b1fqad_func) :: fun
name of external function of one argument which multiplies dbvalu.
real(kind=wp), intent(in), dimension(:) :: xt
knot array for dbvalu
real(kind=wp), intent(in), dimension(n) :: bc
b-coefficient array for dbvalu
integer(kind=ip), intent(in) :: n
number of b-coefficients for dbvalu
integer(kind=ip), intent(in) :: kk
order of the spline, kk>=1
integer(kind=ip), intent(in) :: id
Order of the spline derivative, 0<=id<=kk-1
real(kind=wp), intent(in) :: a
lower limit of integral
real(kind=wp), intent(in) :: b
upper limit of integral (may be less than a)
integer(kind=ip), intent(inout) :: inbv
initialization parameter for dbvalu
real(kind=wp), intent(inout) :: err
IN: is a requested pseudorelative error tolerance. normally pick a value of abs(err)<1e-3. ans will normally have no more error than abs(err) times the integral of the absolute value of fun(x)*dbvalu().
OUT: will be an estimate of the absolute error in ans if the input value of err was negative. (err is unchanged if the input value of err was nonnegative.) the estimated error is solely for information to the user and should not be used as a correction to the computed integral.
real(kind=wp), intent(out) :: ans
computed value of integral
integer(kind=ip), intent(out) :: iflag
a status code:
0: ans most likely meets requested error tolerance, or a=b.
1101: a and b are too nearly equal to allow normal integration. ans is set to zero.
1102: ans probably does not meet requested error tolerance.
real(kind=wp), intent(inout), dimension(:) :: work
work vector of length 3*k for dbvalu
Calls
Called by
Contents
Variables
k l lmn lmx mxl nbits nib nlmx ae anib area c ce ee ef eps est gl glr tol vr x lr aa hh vl gr i1mach14 d1mach5 ln2 sq2 nlmn kmx kml
Subroutines
g8
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: k
integer(kind=ip), private :: l
integer(kind=ip), private :: lmn
integer(kind=ip), private :: lmx
integer(kind=ip), private :: mxl
integer(kind=ip), private :: nbits
integer(kind=ip), private :: nib
integer(kind=ip), private :: nlmx
real(kind=wp), private :: ae
real(kind=wp), private :: anib
real(kind=wp), private :: area
real(kind=wp), private :: c
real(kind=wp), private :: ce
real(kind=wp), private :: ee
real(kind=wp), private :: ef
real(kind=wp), private :: eps
real(kind=wp), private :: est
real(kind=wp), private :: gl
real(kind=wp), private :: glr
real(kind=wp), private :: tol
real(kind=wp), private :: vr
real(kind=wp), private :: x
integer(kind=ip), private, dimension(60) :: lr
real(kind=wp), private, dimension(60) :: aa
real(kind=wp), private, dimension(60) :: hh
real(kind=wp), private, dimension(60) :: vl
real(kind=wp), private, dimension(60) :: gr
integer(kind=ip), private, parameter :: i1mach14 = digits(1.0_wp)
i1mach(14)
real(kind=wp), private, parameter :: d1mach5 = log10(real(radix(x), wp))
d1mach(5)
real(kind=wp), private, parameter :: ln2 = log(2.0_wp)
0.69314718d0
real(kind=wp), private, parameter :: sq2 = sqrt(2.0_wp)
integer(kind=ip), private, parameter :: nlmn = 1
integer(kind=ip), private, parameter :: kmx = 5000
integer(kind=ip), private, parameter :: kml = 6
Subroutines
subroutine g8(x, h, res, iflag)
8-point formula.
Note
Replaced the original double precision abscissa and weight coefficients with the higher precision versions from here: http://pomax.github.io/bezierinfo/legendre-gauss.html So, if wp is changed to say, real128, more precision can be obtained. These coefficients have about 300 digits.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: h
real(kind=wp), intent(out) :: res
integer(kind=ip), intent(out) :: iflag
Call graph
dbsgq8 calls g8
dbvalu calls dintrv
dintrv calls get_temp_x_for_extrap
dbfqad calls dbsgq8
db1fqad calls dbfqad
fintegral_1d calls db1fqad