dbsqad – bspline-fortran
dbsqad Subroutine
80 statements
Source File
private pure subroutine dbsqad(t, bcoef, n, k, x1, x2, bquad, work, iflag)
DBSQAD computes the integral on (x1,x2) of a k-th order b-spline using the b-representation (t,bcoef,n,k). orders k as high as 20 are permitted by applying a 2, 6, or 10 point gauss formula on subintervals of (x1,x2) which are formed by included (distinct) knots.
If orders k greater than 20 are needed, use dbfqad with f(x) = 1.
Note
The maximum number of significant digits obtainable in DBSQAD is the smaller of ~300 and the number of digits carried in real(wp) arithmetic.
References
D. E. Amos, "Quadrature subroutines for splines and B-splines", Report SAND79-1825, Sandia Laboratories, December 1979.
History
Author: Amos, D. E., (SNLA)
800901 DATE WRITTEN
890531 Changed all specific intrinsics to generic. (WRB)
890531 REVISION DATE from Version 3.2
891214 Prologue converted to Version 4.0 format. (BAB)
900315 CALLs to XERROR changed to CALLs to XERMSG. (THJ)
900326 Removed duplicate information from DESCRIPTION section. (WRB)
920501 Reformatted the REFERENCES section. (WRB)
Jacob Williams, 9/6/2017 : refactored to modern Fortran. Added higher precision coefficients.
Note
Extrapolation is not enabled for this routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: t
knot array of length n+k
real(kind=wp), intent(in), dimension(:) :: bcoef
b-spline coefficient array of length n
integer(kind=ip), intent(in) :: n
length of coefficient array
integer(kind=ip), intent(in) :: k
order of b-spline, 1 <= k <= 20
real(kind=wp), intent(in) :: x1
end point of quadrature interval in t(k) <= x <= t(n+1)
real(kind=wp), intent(in) :: x2
end point of quadrature interval in t(k) <= x <= t(n+1)
real(kind=wp), intent(out) :: bquad
integral of the b-spline over (x1,x2)
real(kind=wp), intent(inout), dimension(:) :: work
work vector of length 3*k
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
901: k does not satisfy 1<=k<=20
902: n does not satisfy n>=k
903: x1 or x2 or both do not satisfy t(k)<=x<=t(n+1)
Calls
Called by
Contents
Variables
i il1 il2 ilo inbv jf left m mf mflag npk np1 a aa b bb bma bpa c1 gx q ta tb y1 y2 s gpts gwts
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: i
integer(kind=ip), private :: il1
integer(kind=ip), private :: il2
integer(kind=ip), private :: ilo
integer(kind=ip), private :: inbv
integer(kind=ip), private :: jf
integer(kind=ip), private :: left
integer(kind=ip), private :: m
integer(kind=ip), private :: mf
integer(kind=ip), private :: mflag
integer(kind=ip), private :: npk
integer(kind=ip), private :: np1
real(kind=wp), private :: a
real(kind=wp), private :: aa
real(kind=wp), private :: b
real(kind=wp), private :: bb
real(kind=wp), private :: bma
real(kind=wp), private :: bpa
real(kind=wp), private :: c1
real(kind=wp), private :: gx
real(kind=wp), private :: q
real(kind=wp), private :: ta
real(kind=wp), private :: tb
real(kind=wp), private :: y1
real(kind=wp), private :: y2
real(kind=wp), private, dimension(5) :: s
sum
real(kind=wp), private, parameter, dimension(9) :: gpts = [0.5773502691896257645091487805019574556476017512701268760186023264839776723029333456937153955857495252252087138051355676766566483649996508262705518373647912161760310773007685273559916067003615583077550051041144223011076288835574182229739459904090157105534559538626730166621791266197964892168_wp, 0.2386191860831969086305017216807119354186106301400213501813951645742749342756398422492244272573491316090722230970106872029554530350772051352628872175189982985139866216812636229030578298770859440976999298617585739469216136216592222334626416400139367778945327871453246721518889993399000945406150514997832_wp, 0.6612093864662645136613995950199053470064485643951700708145267058521834966071431009442864037464614564298883716392751466795573467722253804381723198010093367423918538864300079016299442625145884902455718821970386303223620117352321357022187936189069743012315558710642131016398967690135661651261150514997832_wp, 0.9324695142031520278123015544939946091347657377122898248725496165266135008442001962762887399219259850478636797265728341065879713795116384041921786180750210169211578452038930846310372961174632524612619760497437974074226320896716211721783852305051047442772222093863676553669179038880252326771150514997832_wp, 0.1488743389816312108848260011297199846175648594206916957079892535159036173556685213711776297994636912300311608052553388261028901818643765402316761969968090913050737827720371059070942475859422743249837177174247346216914852902942929003193466659082433838094355075996833570230005003837280634351_wp, 0.4333953941292471907992659431657841622000718376562464965027015131437669890777035012251027579501177212236829350409989379472742247577232492051267741032822086200952319270933462032011328320387691584063411149801129823141488787443204324766414421576788807708483879452488118549797039287926964254222_wp, 0.6794095682990244062343273651148735757692947118348094676648171889525585753950749246150785735704803794998339020473993150608367408425766300907682741718202923543197852846977409718369143712013552962837733153108679126932544954854729341324727211680274268486617121011712030227181051010718804444161_wp, 0.8650633666889845107320966884234930485275430149653304525219597318453747551380555613567907289460457706944046310864117651686783001614934535637392729396890950011571349689893051612072435760480900979725923317923795535739290595879776956832427702236942765911483643714816923781701572597289139322313_wp, 0.9739065285171717200779640120844520534282699466923821192312120666965952032346361596257235649562685562582330425187742112150221686014344777799205409587259942436704413695764881258799146633143510758737119877875210567067452435368713683033860909388311646653581707125686970668737259229449284383797_wp]
real(kind=wp), private, parameter, dimension(9) :: gwts = [1.0_wp, 0.4679139345726910473898703439895509948116556057692105353116253199639142016203981270311100925847919823047662687897547971009283625541735029545935635592733866593364825926382559018030281273563502536241704619318259000997569870959005334740800746343768244318081732063691741034162617653462927888917150514997832_wp, 0.3607615730481386075698335138377161116615218927467454822897392402371400378372617183209622019888193479431172091403707985898798902783643210707767872114085818922114502722525757771126000732368828591631602895111800517408136855470744824724861011832599314498172164024255867775267681999309503106873150514997832_wp, 0.1713244923791703450402961421727328935268225014840439823986354397989457605423401546479277054263886697521165220698744043091917471674621759746296492293180314484520671351091683210843717994067668872126692485569940481594293273570249840534338241823632441183746103912052391190442197035702977497812150514997832_wp, 0.295524224714752870173892994651338329421046717026853601354308029755995938217152329270356595793754216722717164401252558386818490789552005826001936342494186966609562718648884168043231305061535867409083051270663865287483901746874726597515954450775158914556548308329986393605934912382356670244_wp, 0.2692667193099963550912269215694693528597599384608837958005632762421534323191792767642266367092527607555958114503686983086929234693811452415564658846634423711656014432259960141729044528030344411297902977067142537534806284608399276575006911686749842814086288868533208042150419508881916391898_wp, 0.2190863625159820439955349342281631924587718705226770898809565436351999106529512812426839931772021927865912168728128876347666269080669475688309211843316656677105269915322077536772652826671027878246851010208832173320064273483254756250668415885349420711613410227291565477768928313300688702802_wp, 0.1494513491505805931457763396576973324025566396694273678354772687532386547266300109459472646347319519140057525610454363382344517067454976014713716011937109528798134828865118770953566439639333773939909201690204649083815618779157522578300343427785361756927642128792412282970150172590842897331_wp, 0.066671344308688137593568809893331792857864834320158145128694881613412064084087101776785509685058877821090054714520419331487507126254403762139304987316994041634495363706400187011242315504393526242450629832718198718647480566044117862086478449236378557180717569208295026105115288152794421677_wp]
Call graph
dbsqad calls dbvalu, dintrv
dbvalu calls dintrv
dintrv calls get_temp_x_for_extrap
db1sqad calls dbsqad
integral_1d calls db1sqad