dbvalu – bspline-fortran
dbvalu Subroutine
109 statements
Source File
private pure subroutine dbvalu(t, a, n, k, ideriv, x, inbv, work, iflag, val, extrap)
Evaluates the b-representation (t,a,n,k) of a b-spline at x for the function value on ideriv=0 or any of its derivatives on ideriv=1,2,...,k-1. right limiting values (right derivatives) are returned except at the right end point x=t(n+1) where left limiting values are computed. the spline is defined on t(k) x t(n+1). dbvalu returns a fatal error message when x is outside of this interval.
To compute left derivatives or left limiting values at a knot t(i), replace n by i-1 and set x=t(i), i=k+1,n+1.
Error Conditions
improper input
History
bvalue written by carl de boor [5]
dbvalu author: amos, d. e., (snla) : date written 800901
revision date 820801
modified array declarations. (jec)
Jacob Williams, 2/24/2015 : extensive refactoring of CMLIB routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: t
knot vector of length n+k
real(kind=wp), intent(in), dimension(n) :: a
b-spline coefficient vector of length n
integer(kind=ip), intent(in) :: n
number of b-spline coefficients. (sum of knot multiplicities-k)
integer(kind=ip), intent(in) :: k
order of the b-spline, k >= 1
integer(kind=ip), intent(in) :: ideriv
order of the derivative, 0 <= ideriv <= k-1. ideriv = 0 returns the b-spline value
real(kind=wp), intent(in) :: x
argument, t(k) <= x <= t(n+1)
integer(kind=ip), intent(inout) :: inbv
an initialization parameter which must be set to 1 the first time dbvalu is called. inbv contains information for efficient processing after the initial call and inbv must not be changed by the user. distinct splines require distinct inbv parameters.
real(kind=wp), intent(inout), dimension(:) :: work
work vector of length at least 3*k
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
401: k does not satisfy k 1
402: n does not satisfy n k
403: ideriv does not satisfy 0 ideriv k
404: x is not greater than or equal to t(k)
405: x is not less than or equal to t(n+1)
406: a left limiting value cannot be obtained at t(k)
real(kind=wp), intent(out) :: val
the interpolated value
logical, intent(in), optional :: extrap
if extrapolation is allowed (if not present, default is False)
Calls
Called by
Contents
Variables
i iderp1 ihi ihmkmj ilo imk imkpj ipj ip1 ip1mj j jj j1 j2 kmider kmj km1 kpk mflag fkmj xt extrapolation_allowed
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: i
integer(kind=ip), private :: iderp1
integer(kind=ip), private :: ihi
integer(kind=ip), private :: ihmkmj
integer(kind=ip), private :: ilo
integer(kind=ip), private :: imk
integer(kind=ip), private :: imkpj
integer(kind=ip), private :: ipj
integer(kind=ip), private :: ip1
integer(kind=ip), private :: ip1mj
integer(kind=ip), private :: j
integer(kind=ip), private :: jj
integer(kind=ip), private :: j1
integer(kind=ip), private :: j2
integer(kind=ip), private :: kmider
integer(kind=ip), private :: kmj
integer(kind=ip), private :: km1
integer(kind=ip), private :: kpk
integer(kind=ip), private :: mflag
real(kind=wp), private :: fkmj
real(kind=wp), private :: xt
logical, private :: extrapolation_allowed
if extrapolation is allowed
Call graph
dbvalu calls dintrv
dintrv calls get_temp_x_for_extrap
db1val_alt calls dbvalu
dbsqad calls dbvalu
db6val calls dbvalu
db2val calls dbvalu
db1val_default calls dbvalu
db3val calls dbvalu
db5val calls dbvalu
db4val calls dbvalu
evaluate_3d calls db3val
evaluate_2d calls db2val
db1sqad calls dbsqad
evaluate_5d calls db5val
db1val calls db1val_alt, db1val_default
dbsgq8 calls g8
evaluate_6d calls db6val
evaluate_4d calls db4val
evaluate_1d calls db1val
dbfqad calls dbsgq8
integral_1d calls db1sqad
db1fqad calls dbfqad
fintegral_1d calls db1fqad