dintrv – bspline-fortran
dintrv Subroutine
83 statements
Source File
private pure subroutine dintrv(xt, lxt, xx, ilo, ileft, mflag, extrap)
Computes the largest integer ileft in 1 ileft lxt such that xt(ileft) x where xt(*) is a subdivision of the x interval. precisely,
         if            x < xt(1)   then ileft=1,   mflag=-1
         if   xt(i) <= x < xt(i+1) then ileft=i,   mflag=0
         if xt(lxt) <= x           then ileft=lxt, mflag=-2
that is, when multiplicities are present in the break point to the left of x, the largest index is taken for ileft.
History
interv written by carl de boor [5]
dintrv author: amos, d. e., (snla) : date written 800901
revision date 820801
Jacob Williams, 2/24/2015 : updated to free-form Fortran.
Jacob Williams, 2/17/2016 : additional refactoring (eliminated GOTOs).
Jacob Williams, 3/4/2017 : added extrapolation option.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: xt
a knot or break point vector of length lxt
integer(kind=ip), intent(in) :: lxt
length of the xt vector
real(kind=wp), intent(in) :: xx
argument
integer(kind=ip), intent(inout) :: ilo
an initialization parameter which must be set to 1 the first time the spline array xt is processed by dintrv. ilo contains information for efficient processing after the initial call and ilo must not be changed by the user. distinct splines require distinct ilo parameters.
integer(kind=ip), intent(out) :: ileft
largest integer satisfying xt(ileft) x
integer(kind=ip), intent(out) :: mflag
signals when x lies out of bounds
logical, intent(in), optional :: extrap
if extrapolation is allowed (if not present, default is False)
Calls
Called by
Contents
Variables
ihi istep middle x
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: ihi
integer(kind=ip), private :: istep
integer(kind=ip), private :: middle
real(kind=wp), private :: x
Call graph
dintrv calls get_temp_x_for_extrap
dbsqad calls dintrv, dbvalu
db6val calls dintrv, dbvalu
db2val calls dintrv, dbvalu
db3val calls dintrv, dbvalu
db5val calls dintrv, dbvalu
dbvalu calls dintrv
dbfqad calls dintrv, dbsgq8
db4val calls dintrv, dbvalu
evaluate_3d calls db3val
evaluate_2d calls db2val
db1sqad calls dbsqad
evaluate_5d calls db5val
db1val_alt calls dbvalu
db1val_default calls dbvalu
evaluate_6d calls db6val
evaluate_4d calls db4val
db1fqad calls dbfqad
integral_1d calls db1sqad
dbsgq8 calls g8
fintegral_1d calls db1fqad
db1val calls db1val_alt, db1val_default
evaluate_1d calls db1val