fintegral_1d – bspline-fortran
fintegral_1d Subroutine
17 statements
Source File
private subroutine fintegral_1d(me, fun, idx, x1, x2, tol, f, iflag)
Evaluate a bspline_1d definite integral. This is a wrapper for db1fqad.
Arguments
Type Intent Optional Attributes Name
class(bspline_1d), intent(inout) :: me
procedure(b1fqad_func) :: fun
external function of one argument for the integrand bf(x)=fun(x)*dbvalu(tx,bcoef,nx,kx,idx,x,inbv)
integer(kind=ip), intent(in) :: idx
order of the spline derivative, 0 <= idx <= k-1 idx=0 gives the spline function
real(kind=wp), intent(in) :: x1
left point of interval
real(kind=wp), intent(in) :: x2
right point of interval
real(kind=wp), intent(in) :: tol
desired accuracy for the quadrature
real(kind=wp), intent(out) :: f
integral of bf(x) over
integer(kind=ip), intent(out) :: iflag
status flag (see db1sqad)
Calls
Contents
None
Call graph
fintegral_1d calls db1fqad
db1fqad calls dbfqad
dbfqad calls dintrv, dbsgq8
dintrv calls get_temp_x_for_extrap
dbsgq8 calls g8
dbvalu calls dintrv