get_temp_x_for_extrap – bspline-fortran
get_temp_x_for_extrap Function
25 statements
Source File
private pure function get_temp_x_for_extrap(x, tmin, tmax, extrap) result(xt)
Returns the value of x to use for computing the interval in t, depending on if extrapolation is allowed or not.
If extrapolation is allowed and x is < tmin or > tmax, then either tmin or tmax - 2.0_wp*spacing(tmax) is returned. Otherwise, x is returned.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
variable value
real(kind=wp), intent(in) :: tmin
first knot vector element for b-splines
real(kind=wp), intent(in) :: tmax
last knot vector element for b-splines
logical, intent(in), optional :: extrap
if extrapolation is allowed (if not present, default is False)
Return Value real(kind=wp)
The value returned (it will either be tmin, x, or tmax)
Called by
Contents
Variables
extrapolation_allowed
Variables
Type Visibility Attributes Name Initial
logical, private :: extrapolation_allowed
if extrapolation is allowed
Call graph
dintrv calls get_temp_x_for_extrap
db4val calls dintrv, dbvalu
dbfqad calls dintrv, dbsgq8
dbvalu calls dintrv
db2val calls dintrv, dbvalu
dbsqad calls dintrv, dbvalu
db3val calls dintrv, dbvalu
db5val calls dintrv, dbvalu
db6val calls dintrv, dbvalu
db1fqad calls dbfqad
evaluate_2d calls db2val
evaluate_6d calls db6val
db1val_alt calls dbvalu
evaluate_5d calls db5val
evaluate_4d calls db4val
db1sqad calls dbsqad
db1val_default calls dbvalu
evaluate_3d calls db3val
dbsgq8 calls g8
db1val calls db1val_alt, db1val_default
fintegral_1d calls db1fqad
integral_1d calls db1sqad
evaluate_1d calls db1val