initialize_2d_auto_knots – bspline-fortran
initialize_2d_auto_knots Subroutine
32 statements
Source File
private pure subroutine initialize_2d_auto_knots(me, x, y, fcn, kx, ky, iflag, extrap)
Initialize a bspline_2d type (with automatically-computed knots). This is a wrapper for db2ink.
Arguments
Type Intent Optional Attributes Name
class(bspline_2d), intent(inout) :: me
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:) :: fcn
(nx,ny) matrix of function values to interpolate. fcn(i,j) should contain the function value at the point (x(i),y(j))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(out) :: iflag
status flag (see db2ink)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Calls
Called by
Contents
Variables
iknot nx ny
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: iknot
integer(kind=ip), private :: nx
integer(kind=ip), private :: ny
Call graph
initialize_2d_auto_knots calls db2ink
db2ink calls dbtpcf, dbknot, check_inputs
dbtpcf calls dbintk, dbnslv
check_inputs calls check
dbintk calls dbnslv, dbnfac, dbspvn
bspline_2d_constructor_auto_knots calls initialize_2d_auto_knots
bspline_2d calls bspline_2d_constructor_auto_knots