initialize_1d_specify_knots – bspline-fortran
initialize_1d_specify_knots Subroutine
26 statements
Source File
private pure subroutine initialize_1d_specify_knots(me, x, fcn, kx, tx, iflag, extrap)
Initialize a bspline_1d type (with user-specified knots). This is a wrapper for db1ink.
Arguments
Type Intent Optional Attributes Name
class(bspline_1d), intent(inout) :: me
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
real(kind=wp), intent(in), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant. Must be non-decreasing.
integer(kind=ip), intent(out) :: iflag
status flag (see db1ink)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Calls
Called by
Contents
Variables
nx
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: nx
Call graph
initialize_1d_specify_knots calls db1ink, check_knot_vectors_sizes
db1ink calls db1ink_alt, db1ink_default, db1ink_alt_2
db1ink_alt calls dbint4, check_inputs
db1ink_default calls dbtpcf, check_inputs, dbknot
db1ink_alt_2 calls dbint4, check_inputs
dbint4 calls dbspvd, dbnfac, dbnslv
dbtpcf calls dbintk, dbnslv
check_inputs calls check
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_1d calls bspline_1d_constructor_specify_knots