initialize_4d_auto_knots – bspline-fortran
initialize_4d_auto_knots Subroutine
46 statements
Source File
private pure subroutine initialize_4d_auto_knots(me, x, y, z, q, fcn, kx, ky, kz, kq, iflag, extrap)
Initialize a bspline_4d type (with automatically-computed knots). This is a wrapper for db4ink.
Arguments
Type Intent Optional Attributes Name
class(bspline_4d), intent(inout) :: me
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: y
(ny) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: z
(nz) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:) :: q
(nq) array of abcissae. Must be strictly increasing.
real(kind=wp), intent(in), dimension(:,:,:,:) :: fcn
(nx,ny,nz,nq) matrix of function values to interpolate. fcn(i,j,k,l) should contain the function value at the point (x(i),y(j),z(k),q(l))
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: ky
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kz
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: kq
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(out) :: iflag
status flag (see db4ink)
logical, intent(in), optional :: extrap
if true, then extrapolation is allowed (default is false)
Calls
Called by
Contents
Variables
iknot nx ny nz nq
Variables
Type Visibility Attributes Name Initial
integer(kind=ip), private :: iknot
integer(kind=ip), private :: nx
integer(kind=ip), private :: ny
integer(kind=ip), private :: nz
integer(kind=ip), private :: nq
Call graph
initialize_4d_auto_knots calls db4ink
db4ink calls dbtpcf, check_inputs, dbknot
dbtpcf calls dbintk, dbnslv
check_inputs calls check
dbintk calls dbnslv, dbnfac, dbspvn
bspline_4d_constructor_auto_knots calls initialize_4d_auto_knots
bspline_4d calls bspline_4d_constructor_auto_knots