db1ink – bspline-fortran
db1ink Interface
3 statements
Source File
public interface db1ink
1D initialization routines.
Calls
Called by
Contents
Module Procedures
db1ink_default db1ink_alt db1ink_alt_2
Module Procedures
private pure subroutine db1ink_default(x, nx, fcn, kx, iknot, tx, bcoef, iflag)
Determines the parameters of a function that interpolates the one-dimensional gridded data The interpolating function and its derivatives may subsequently be evaluated by the function db1val.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
(nx) array of abcissae. Must be strictly increasing.
integer(kind=ip), intent(in) :: nx
Number of abcissae
real(kind=wp), intent(in), dimension(:) :: fcn
(nx) array of function values to interpolate. fcn(i) should contain the function value at the point x(i)
integer(kind=ip), intent(in) :: kx
The order of spline pieces in () (order = polynomial degree + 1)
integer(kind=ip), intent(in) :: iknot
knot sequence flag:
0 = knot sequence chosen by db1ink.
1 = knot sequence chosen by user.
real(kind=wp), intent(inout), dimension(:) :: tx
The (nx+kx) knots in the direction for the spline interpolant:
If iknot=0 these are chosen by db1ink.
If iknot=1 these are specified by the user.
Must be non-decreasing.
real(kind=wp), intent(out), dimension(:) :: bcoef
(nx) array of coefficients of the b-spline interpolant.
integer(kind=ip), intent(out) :: iflag
status flag:
0 = successful execution.
2 = iknot out of range.
3 = nx out of range.
4 = kx out of range.
5 = x not strictly increasing.
6 = tx not non-decreasing.
700 = size(x) size(fcn,1).
706 = size(x) nx.
712 = size(tx) nx+kx.
800 = size(x) size(bcoef,1).
private pure subroutine db1ink_alt(x, nx, fcn, kx, ibcl, ibcr, fbcl, fbcr, kntopt, tx, bcoef, iflag)
Alternate version of db1ink_default, where the boundary conditions can be specified.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
vector of abscissae of length nx, distinct and in increasing order
integer(kind=ip), intent(in) :: nx
number of data points,
real(kind=wp), intent(in), dimension(:) :: fcn
vector of ordinates of length nx
integer(kind=ip), intent(in) :: kx
spline order (Currently, this must be 4)
integer(kind=ip), intent(in) :: ibcl
selection parameter for left boundary condition:
ibcl = 1 constrain the first derivative at x(1) to fbcl
ibcl = 2 constrain the second derivative at x(1) to fbcl
integer(kind=ip), intent(in) :: ibcr
selection parameter for right boundary condition:
ibcr = 1 constrain first derivative at x(nx) to fbcr
ibcr = 2 constrain second derivative at x(nx) to fbcr
real(kind=wp), intent(in) :: fbcl
left boundary values governed by ibcl
real(kind=wp), intent(in) :: fbcr
right boundary values governed by ibcr
integer(kind=ip), intent(in) :: kntopt
knot selection parameter:
kntopt = 1 sets knot multiplicity at t(4) and t(nx+3) to 4
kntopt = 2 sets a symmetric placement of knots about t(4) and t(nx+3)
real(kind=wp), intent(out), dimension(:) :: tx
knot array of length nx+6
real(kind=wp), intent(out), dimension(:) :: bcoef
b spline coefficient array of length nx+2
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
806: dbint4 can only be used when k=4
private pure subroutine db1ink_alt_2(x, nx, fcn, kx, ibcl, ibcr, fbcl, fbcr, tleft, tright, tx, bcoef, iflag)
Alternate version of db1ink_alt, where the first and last 3 knots are specified by the user.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: x
vector of abscissae of length nx, distinct and in increasing order
integer(kind=ip), intent(in) :: nx
number of data points,
real(kind=wp), intent(in), dimension(:) :: fcn
vector of ordinates of length nx
integer(kind=ip), intent(in) :: kx
spline order (Currently, this must be 4)
integer(kind=ip), intent(in) :: ibcl
selection parameter for left boundary condition:
ibcl = 1 constrain the first derivative at x(1) to fbcl
ibcl = 2 constrain the second derivative at x(1) to fbcl
integer(kind=ip), intent(in) :: ibcr
selection parameter for right boundary condition:
ibcr = 1 constrain first derivative at x(nx) to fbcr
ibcr = 2 constrain second derivative at x(nx) to fbcr
real(kind=wp), intent(in) :: fbcl
left boundary values governed by ibcl
real(kind=wp), intent(in) :: fbcr
right boundary values governed by ibcr
real(kind=wp), intent(in), dimension(3) :: tleft
t(1:3) in increasing order supplied by the user.
real(kind=wp), intent(in), dimension(3) :: tright
t(nx+4:nx+6) in increasing order supplied by the user.
real(kind=wp), intent(out), dimension(:) :: tx
knot array of length nx+6
real(kind=wp), intent(out), dimension(:) :: bcoef
b spline coefficient array of length nx+2
integer(kind=ip), intent(out) :: iflag
status flag:
0: no errors
806: dbint4 can only be used when k=4
Call graph
db1ink calls db1ink_default, db1ink_alt_2, db1ink_alt
db1ink_default calls dbtpcf, dbknot, check_inputs
db1ink_alt_2 calls dbint4, check_inputs
db1ink_alt calls dbint4, check_inputs
dbtpcf calls dbintk, dbnslv
dbint4 calls dbnfac, dbnslv, dbspvd
check_inputs calls check
dbintk calls dbnfac, dbnslv, dbspvn
dbspvd calls dbspvn
initialize_1d_specify_knots calls db1ink
initialize_1d_auto_knots calls db1ink
bspline_1d_constructor_auto_knots calls initialize_1d_auto_knots
bspline_1d_constructor_specify_knots calls initialize_1d_specify_knots
bspline_1d calls bspline_1d_constructor_auto_knots, bspline_1d_constructor_specify_knots